"""BasketKeep ranking sources — August 27, 2026.

Compiled dynasty and redraft boards for category + points leagues.
The Keep is the dynasty Super Aggregate. The Board is this-year redraft.
Unranked names are skipped in the mean — never treated as 999.
"""
from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

from bk_curve import bk_value

ROOT = Path(__file__).resolve().parents[1]

# Dynasty order is the list order. Age is as of opening night 2026-27.
# (name, pos, team, age)
UNIVERSE = [
    ("Victor Wembanyama", "C", "SAS", 22),
    ("Shai Gilgeous-Alexander", "PG", "OKC", 27),
    ("Luka Doncic", "PG", "LAL", 27),
    ("Anthony Edwards", "SG", "MIN", 25),
    ("Cooper Flagg", "SF", "UTA", 19),
    ("Cade Cunningham", "PG", "DET", 24),
    ("Paolo Banchero", "PF", "ORL", 23),
    ("Chet Holmgren", "C", "OKC", 24),
    ("Amen Thompson", "SG", "HOU", 23),
    ("Franz Wagner", "SF", "ORL", 25),
    ("Nikola Jokic", "C", "DEN", 31),
    ("Giannis Antetokounmpo", "PF", "MIL", 31),
    ("Jalen Williams", "SF", "OKC", 25),
    ("Tyrese Maxey", "PG", "PHI", 25),
    ("Jalen Brunson", "PG", "NYK", 29),
    ("Anthony Black", "PG", "ORL", 22),
    ("Stephon Castle", "PG", "SAS", 21),
    ("Scoot Henderson", "PG", "POR", 22),
    ("Ausar Thompson", "SF", "DET", 23),
    ("Reed Sheppard", "PG", "HOU", 22),
    ("Dylan Harper", "PG", "WAS", 19),
    ("Ace Bailey", "SF", "UTA", 19),
    ("Alexandre Sarr", "C", "WAS", 21),
    ("Donovan Clingan", "C", "POR", 21),
    ("Jalen Duren", "C", "DET", 22),
    ("Alperen Sengun", "C", "HOU", 24),
    ("Scottie Barnes", "SF", "TOR", 25),
    ("Jaren Jackson Jr.", "PF", "MEM", 26),
    ("Evan Mobley", "C", "CLE", 25),
    ("Bam Adebayo", "C", "MIA", 29),
    ("Karl-Anthony Towns", "C", "NYK", 30),
    ("Domantas Sabonis", "C", "SAC", 30),
    ("Trae Young", "PG", "ATL", 27),
    ("LaMelo Ball", "PG", "CHA", 25),
    ("Ja Morant", "PG", "MEM", 27),
    ("De'Aaron Fox", "PG", "SAS", 28),
    ("Tyrese Haliburton", "PG", "IND", 26),
    ("Darius Garland", "PG", "CLE", 26),
    ("Jamison Battle", "SF", "TOR", 25),
    ("Jalen Johnson", "PF", "ATL", 24),
    ("Josh Giddey", "SG", "CHI", 24),
    ("Bennedict Mathurin", "SG", "IND", 24),
    ("Brandon Miller", "SF", "CHA", 23),
    ("Bilal Coulibaly", "SF", "WAS", 22),
    ("Keyonte George", "SG", "UTA", 23),
    ("Gradey Dick", "SG", "TOR", 22),
    ("Jaime Jaquez Jr.", "SF", "MIA", 25),
    ("Cam Whitmore", "SF", "HOU", 22),
    ("Taylor Hendricks", "PF", "UTA", 22),
    ("Dereck Lively II", "C", "DAL", 22),
    ("Zach Edey", "C", "MEM", 24),
    ("Matas Buzelis", "SF", "CHI", 21),
    ("Rob Dillingham", "PG", "MIN", 21),
    ("Ron Holland", "SF", "DET", 21),
    ("Tidjane Salaun", "SF", "CHA", 20),
    ("Dalton Knecht", "SF", "LAL", 25),
    ("Zaccharie Risacher", "SF", "ATL", 21),
    ("Reed Sheppard", "PG", "HOU", 22),
    ("AJ Dybantsa", "SF", "BOS", 19),
    ("Cameron Boozer", "PF", "CHI", 19),
    ("Darryn Peterson", "SG", "OKC", 19),
    ("Jalen Suggs", "SG", "ORL", 25),
    ("Desmond Bane", "SG", "ORL", 28),
    ("Mikal Bridges", "SF", "NYK", 30),
    ("OG Anunoby", "SF", "NYK", 29),
    ("Jaylen Brown", "SG", "BOS", 29),
    ("Jayson Tatum", "SF", "BOS", 28),
    ("Jaylen Wells", "SF", "MEM", 23),
    ("Tari Eason", "PF", "HOU", 25),
    ("Amen Thompson", "SG", "HOU", 23),
    ("Dyson Daniels", "SG", "ATL", 23),
    ("Toumani Camara", "SF", "POR", 26),
    ("Keegan Murray", "PF", "SAC", 26),
    ("Trey Murphy III", "SF", "NOP", 26),
    ("Herb Jones", "SF", "NOP", 28),
    ("Dillon Brooks", "SF", "HOU", 30),
    ("Austin Reaves", "SG", "LAL", 28),
    ("Norman Powell", "SG", "LAC", 33),
    ("Anfernee Simons", "SG", "BOS", 27),
    ("CJ McCollum", "SG", "NOP", 35),
    ("Tyler Herro", "SG", "MIA", 26),
    ("Donovan Mitchell", "SG", "CLE", 30),
    ("Devin Booker", "SG", "PHX", 29),
    ("Anthony Davis", "C", "DAL", 33),
    ("Kawhi Leonard", "SF", "LAC", 35),
    ("Paul George", "SF", "PHI", 36),
    ("LeBron James", "SF", "LAL", 41),
    ("Stephen Curry", "PG", "GSW", 38),
    ("Kevin Durant", "PF", "HOU", 38),
    ("James Harden", "PG", "LAC", 37),
    ("Kyrie Irving", "PG", "DAL", 34),
    ("Zion Williamson", "PF", "NOP", 26),
    ("Lauri Markkanen", "PF", "UTA", 29),
    ("Pascal Siakam", "PF", "IND", 32),
    ("Jimmy Butler", "SF", "GSW", 37),
    ("DeMar DeRozan", "SF", "SAC", 37),
    ("Zach LaVine", "SG", "SAC", 31),
    ("Brandon Ingram", "SF", "TOR", 29),
    ("RJ Barrett", "SG", "TOR", 26),
    ("Immanuel Quickley", "PG", "TOR", 27),
    ("Scottie Barnes", "SF", "TOR", 25),
    ("Jakob Poeltl", "C", "TOR", 31),
    ("Ivica Zubac", "C", "LAC", 29),
    ("Walker Kessler", "C", "UTA", 25),
    ("Nic Claxton", "C", "BKN", 27),
    ("Jarrett Allen", "C", "CLE", 28),
    ("Myles Turner", "C", "MIL", 30),
    ("Brook Lopez", "C", "LAC", 38),
    ("Rudy Gobert", "C", "MIN", 34),
    ("Naz Reid", "C", "MIN", 27),
    ("Julius Randle", "PF", "MIN", 31),
    ("Rudy Gobert", "C", "MIN", 34),
    ("Nickeil Alexander-Walker", "SG", "MIN", 28),
    ("Jaden McDaniels", "SF", "MIN", 25),
    ("Naz Reid", "C", "MIN", 27),
    ("Rudy Gobert", "C", "MIN", 34),
    ("Mike Conley", "PG", "MIN", 39),
    ("Donte DiVincenzo", "SG", "MIN", 29),
    ("Naz Reid", "C", "MIN", 27),
    ("Cam Thomas", "SG", "BKN", 25),
    ("Nic Claxton", "C", "BKN", 27),
    ("Cameron Johnson", "SF", "BKN", 30),
    ("Day'Ron Sharpe", "C", "BKN", 25),
    ("Noah Clowney", "PF", "BKN", 22),
    ("Dariq Whitehead", "SF", "BKN", 22),
    ("Ziaire Williams", "SF", "BKN", 25),
    ("Keon Johnson", "SG", "BKN", 24),
    ("Tyrese Martin", "SG", "BKN", 27),
    ("Jalen Wilson", "SF", "BKN", 26),
    ("Trendon Watford", "PF", "BKN", 25),
    ("D'Angelo Russell", "PG", "BKN", 30),
    ("Dennis Schroder", "PG", "SAC", 33),
    ("Malik Monk", "SG", "SAC", 28),
    ("DeMar DeRozan", "SF", "SAC", 37),
    ("Keegan Murray", "PF", "SAC", 26),
    ("Domantas Sabonis", "C", "SAC", 30),
    ("Keon Ellis", "SG", "SAC", 26),
    ("Trey Lyles", "PF", "SAC", 30),
    ("Isaac Jones", "PF", "SAC", 25),
    ("Devin Carter", "SG", "SAC", 24),
    ("Jordan Clarkson", "SG", "NYK", 34),
    ("Mikal Bridges", "SF", "NYK", 30),
    ("OG Anunoby", "SF", "NYK", 29),
    ("Josh Hart", "SF", "NYK", 31),
    ("Karl-Anthony Towns", "C", "NYK", 30),
    ("Mitchell Robinson", "C", "NYK", 28),
    ("Miles McBride", "PG", "NYK", 26),
    ("Tyler Kolek", "PG", "NYK", 24),
    ("Pacome Dadiet", "SF", "NYK", 21),
    ("Ariel Hukporti", "C", "NYK", 24),
    ("Cameron Payne", "PG", "NYK", 32),
    ("Landry Shamet", "SG", "NYK", 29),
    ("Precious Achiuwa", "PF", "NYK", 27),
    ("Jericho Sims", "C", "NYK", 27),
    ("Payton Pritchard", "PG", "BOS", 28),
    ("Derrick White", "SG", "BOS", 32),
    ("Jaylen Brown", "SG", "BOS", 29),
    ("Jayson Tatum", "SF", "BOS", 28),
    ("Kristaps Porzingis", "C", "BOS", 31),
    ("Jrue Holiday", "PG", "BOS", 36),
    ("Sam Hauser", "SF", "BOS", 28),
    ("Neemias Queta", "C", "BOS", 27),
    ("Baylor Scheierman", "SG", "BOS", 25),
    ("Jordan Walsh", "SF", "BOS", 22),
    ("Jaden Springer", "SG", "BOS", 24),
    ("Luke Kornet", "C", "BOS", 31),
    ("Xavier Tillman", "C", "BOS", 27),
    ("Anfernee Simons", "SG", "BOS", 27),
    ("Max Strus", "SF", "CLE", 30),
    ("Donovan Mitchell", "SG", "CLE", 30),
    ("Darius Garland", "PG", "CLE", 26),
    ("Evan Mobley", "C", "CLE", 25),
    ("Jarrett Allen", "C", "CLE", 28),
    ("Dean Wade", "PF", "CLE", 29),
    ("Isaac Okoro", "SF", "CLE", 25),
    ("Sam Merrill", "SG", "CLE", 30),
    ("Craig Porter Jr.", "PG", "CLE", 26),
    ("Georges Niang", "PF", "CLE", 33),
    ("Ty Jerome", "SG", "CLE", 29),
    ("Caris LeVert", "SG", "ATL", 32),
    ("Trae Young", "PG", "ATL", 27),
    ("Dyson Daniels", "SG", "ATL", 23),
    ("Zaccharie Risacher", "SF", "ATL", 21),
    ("Jalen Johnson", "PF", "ATL", 24),
    ("Onyeka Okongwu", "C", "ATL", 25),
    ("Clint Capela", "C", "ATL", 32),
    ("Vit Krejci", "SG", "ATL", 26),
    ("Garrison Mathews", "SG", "ATL", 29),
    ("Kobe Bufkin", "PG", "ATL", 23),
    ("Mouhamed Gueye", "PF", "ATL", 23),
    ("Larry Nance Jr.", "PF", "ATL", 33),
    ("Dejounte Murray", "SG", "NOP", 29),
    ("CJ McCollum", "SG", "NOP", 35),
    ("Trey Murphy III", "SF", "NOP", 26),
    ("Zion Williamson", "PF", "NOP", 26),
    ("Yves Missi", "C", "NOP", 22),
    ("Herb Jones", "SF", "NOP", 28),
    ("Jordan Hawkins", "SG", "NOP", 24),
    ("Jose Alvarado", "PG", "NOP", 28),
    ("Kelly Olynyk", "C", "NOP", 35),
    ("Brandon Boston Jr.", "SG", "NOP", 25),
    ("Karlo Matkovic", "PF", "NOP", 25),
    ("Trey Jemison", "C", "NOP", 26),
    ("Daniel Theis", "C", "NOP", 34),
    ("Coby White", "SG", "CHI", 26),
    ("Josh Giddey", "SG", "CHI", 24),
    ("Matas Buzelis", "SF", "CHI", 21),
    ("Patrick Williams", "PF", "CHI", 25),
    ("Nikola Vucevic", "C", "CHI", 35),
    ("Ayo Dosunmu", "SG", "CHI", 26),
    ("Julian Phillips", "SF", "CHI", 23),
    ("Dalen Terry", "SG", "CHI", 24),
    ("Jalen Smith", "C", "CHI", 26),
    ("Lonzo Ball", "PG", "CLE", 28),
    ("Zach Collins", "C", "CHI", 28),
    ("Chris Duarte", "SG", "CHI", 29),
    ("Torrey Craig", "SF", "CHI", 35),
    ("Cameron Boozer", "PF", "CHI", 19),
    ("LaMelo Ball", "PG", "CHA", 25),
    ("Brandon Miller", "SF", "CHA", 23),
    ("Tidjane Salaun", "SF", "CHA", 20),
    ("Mark Williams", "C", "CHA", 24),
    ("Nick Richards", "C", "CHA", 28),
    ("Tre Mann", "PG", "CHA", 25),
    ("Josh Green", "SG", "CHA", 25),
    ("Grant Williams", "PF", "CHA", 27),
    ("Moussa Diabate", "PF", "CHA", 24),
    ("KJ Simpson", "PG", "CHA", 23),
    ("Seth Curry", "SG", "CHA", 36),
    ("Taj Gibson", "C", "CHA", 41),
    ("Vasilije Micic", "PG", "CHA", 32),
    ("Cody Martin", "SF", "CHA", 30),
    ("Miles Bridges", "SF", "CHA", 28),
    ("Jalen Green", "SG", "PHX", 24),
    ("Devin Booker", "SG", "PHX", 29),
    ("Ryan Dunn", "SF", "PHX", 23),
    ("Royce O'Neale", "SF", "PHX", 33),
    ("Jusuf Nurkic", "C", "PHX", 32),
    ("Grayson Allen", "SG", "PHX", 30),
    ("Bradley Beal", "SG", "PHX", 33),
    ("Mason Plumlee", "C", "PHX", 36),
    ("Oso Ighodaro", "PF", "PHX", 23),
    ("Tyus Jones", "PG", "PHX", 30),
    ("Monte Morris", "PG", "PHX", 31),
    ("Bol Bol", "C", "PHX", 26),
    ("Damion Lee", "SG", "PHX", 33),
    ("Collin Gillespie", "PG", "PHX", 27),
    ("Aaron Gordon", "PF", "DEN", 31),
    ("Nikola Jokic", "C", "DEN", 31),
    ("Jamal Murray", "PG", "DEN", 29),
    ("Michael Porter Jr.", "SF", "DEN", 28),
    ("Christian Braun", "SG", "DEN", 25),
    ("Peyton Watson", "SF", "DEN", 24),
    ("Julian Strawther", "SG", "DEN", 24),
    ("Russell Westbrook", "PG", "DEN", 37),
    ("Dario Saric", "PF", "DEN", 32),
    ("Hunter Tyson", "SF", "DEN", 26),
    ("Zeke Nnaji", "PF", "DEN", 25),
    ("Jalen Pickett", "PG", "DEN", 27),
    ("Vlatko Cancar", "SF", "DEN", 29),
    ("Trey Alexander", "SG", "DEN", 23),
    ("Giannis Antetokounmpo", "PF", "MIL", 31),
    ("Damian Lillard", "PG", "MIL", 36),
    ("Khris Middleton", "SF", "WAS", 35),
    ("Brook Lopez", "C", "LAC", 38),
    ("Myles Turner", "C", "MIL", 30),
    ("Gary Trent Jr.", "SG", "MIL", 27),
    ("Bobby Portis", "PF", "MIL", 31),
    ("AJ Green", "SG", "MIL", 26),
    ("Andre Jackson Jr.", "SG", "MIL", 24),
    ("Ryan Rollins", "PG", "MIL", 24),
    ("Taurean Prince", "SF", "MIL", 32),
    ("MarJon Beauchamp", "SF", "NYK", 25),
    ("Pat Connaughton", "SG", "MIL", 33),
    ("Delon Wright", "PG", "NYK", 34),
    ("Thanasis Antetokounmpo", "SF", "MIL", 34),
    ("Shai Gilgeous-Alexander", "PG", "OKC", 27),
    ("Jalen Williams", "SF", "OKC", 25),
    ("Chet Holmgren", "C", "OKC", 24),
    ("Luguentz Dort", "SG", "OKC", 27),
    ("Isaiah Joe", "SG", "OKC", 27),
    ("Aaron Wiggins", "SG", "OKC", 27),
    ("Cason Wallace", "PG", "OKC", 23),
    ("Isaiah Hartenstein", "C", "OKC", 28),
    ("Kenrich Williams", "PF", "OKC", 31),
    ("Alex Caruso", "SG", "OKC", 32),
    ("Jaylin Williams", "PF", "OKC", 24),
    ("Ajay Mitchell", "PG", "OKC", 24),
    ("Dillon Jones", "SF", "OKC", 24),
    ("Nikola Topic", "PG", "OKC", 21),
    ("Darryn Peterson", "SG", "OKC", 19),
    ("Ousmane Dieng", "SF", "OKC", 23),
    ("Amen Thompson", "SG", "HOU", 23),
    ("Jalen Green", "SG", "PHX", 24),
    ("Fred VanVleet", "PG", "HOU", 32),
    ("Dillon Brooks", "SF", "HOU", 30),
    ("Alperen Sengun", "C", "HOU", 24),
    ("Tari Eason", "PF", "HOU", 25),
    ("Jabari Smith Jr.", "PF", "HOU", 23),
    ("Reed Sheppard", "PG", "HOU", 22),
    ("Cam Whitmore", "SF", "HOU", 22),
    ("Steven Adams", "C", "HOU", 33),
    ("Aaron Holiday", "PG", "HOU", 29),
    ("Jae'Sean Tate", "SF", "HOU", 30),
    ("Jeff Green", "PF", "HOU", 40),
    ("Jock Landale", "C", "HOU", 30),
    ("Kevin Durant", "PF", "HOU", 38),
    ("Amen Thompson", "SG", "HOU", 23),
    ("Luka Doncic", "PG", "LAL", 27),
    ("Austin Reaves", "SG", "LAL", 28),
    ("LeBron James", "SF", "LAL", 41),
    ("Rui Hachimura", "PF", "LAL", 28),
    ("Dalton Knecht", "SF", "LAL", 25),
    ("Dorian Finney-Smith", "SF", "LAL", 33),
    ("Gabe Vincent", "PG", "LAL", 30),
    ("Jaxson Hayes", "C", "LAL", 26),
    ("Max Christie", "SG", "DAL", 23),
    ("Bronny James", "SG", "LAL", 22),
    ("Christian Koloko", "C", "LAL", 26),
    ("Shake Milton", "SG", "LAL", 30),
    ("Cam Reddish", "SF", "LAL", 27),
    ("Anthony Davis", "C", "DAL", 33),
    ("Kyrie Irving", "PG", "DAL", 34),
    ("Klay Thompson", "SG", "DAL", 36),
    ("P.J. Washington", "PF", "DAL", 27),
    ("Dereck Lively II", "C", "DAL", 22),
    ("Naji Marshall", "SF", "DAL", 28),
    ("Spencer Dinwiddie", "PG", "DAL", 33),
    ("Dante Exum", "SG", "DAL", 31),
    ("Daniel Gafford", "C", "DAL", 28),
    ("Olivier-Maxence Prosper", "SF", "DAL", 24),
    ("Jaden Hardy", "SG", "DAL", 24),
    ("Kessler Edwards", "SF", "DAL", 26),
    ("Dwight Powell", "C", "DAL", 35),
    ("Maxi Kleber", "PF", "DAL", 34),
    ("Kyrie Irving", "PG", "DAL", 34),
    ("James Harden", "PG", "LAC", 37),
    ("Kawhi Leonard", "SF", "LAC", 35),
    ("Norman Powell", "SG", "LAC", 33),
    ("Ivica Zubac", "C", "LAC", 29),
    ("Derrick Jones Jr.", "SF", "LAC", 29),
    ("Amir Coffey", "SF", "LAC", 29),
    ("Kris Dunn", "PG", "LAC", 32),
    ("Nicolas Batum", "PF", "LAC", 37),
    ("Mo Bamba", "C", "LAC", 28),
    ("Bones Hyland", "PG", "LAC", 26),
    ("Terance Mann", "SG", "BKN", 29),
    ("Jordan Miller", "SF", "LAC", 26),
    ("Kai Jones", "C", "LAC", 25),
    ("Kobe Brown", "PF", "LAC", 26),
    ("Stephen Curry", "PG", "GSW", 38),
    ("Jimmy Butler", "SF", "GSW", 37),
    ("Draymond Green", "PF", "GSW", 36),
    ("Andrew Wiggins", "SF", "MIA", 31),
    ("Brandin Podziemski", "SG", "GSW", 23),
    ("Trayce Jackson-Davis", "C", "GSW", 26),
    ("Moses Moody", "SG", "GSW", 24),
    ("Buddy Hield", "SG", "GSW", 33),
    ("Gary Payton II", "SG", "GSW", 33),
    ("Kevon Looney", "C", "GSW", 30),
    ("Gui Santos", "SF", "GSW", 24),
    ("Lindy Waters III", "SG", "GSW", 29),
    ("Pat Spencer", "PG", "GSW", 30),
    ("Quinten Post", "C", "GSW", 26),
    ("Kyle Anderson", "PF", "GSW", 33),
    ("De'Aaron Fox", "PG", "SAS", 28),
    ("Victor Wembanyama", "C", "SAS", 22),
    ("Stephon Castle", "PG", "SAS", 21),
    ("Harrison Barnes", "SF", "SAS", 34),
    ("Jeremy Sochan", "PF", "SAS", 23),
    ("Keldon Johnson", "SF", "SAS", 26),
    ("Julian Champagnie", "SF", "SAS", 25),
    ("Chris Paul", "PG", "LAC", 41),
    ("Tre Jones", "PG", "CHI", 26),
    ("Devin Vassell", "SG", "SAS", 26),
    ("Zach Collins", "C", "CHI", 28),
    ("Sandro Mamukelashvili", "C", "SAS", 27),
    ("Blake Wesley", "SG", "SAS", 23),
    ("Sidy Cissoko", "SF", "SAS", 22),
    ("Charles Bassey", "C", "SAS", 25),
    ("Cade Cunningham", "PG", "DET", 24),
    ("Jalen Duren", "C", "DET", 22),
    ("Ausar Thompson", "SF", "DET", 23),
    ("Ron Holland", "SF", "DET", 21),
    ("Tobias Harris", "PF", "DET", 34),
    ("Tim Hardaway Jr.", "SG", "DET", 34),
    ("Isaiah Stewart", "C", "DET", 25),
    ("Malik Beasley", "SG", "DET", 29),
    ("Simone Fontecchio", "SF", "DET", 30),
    ("Marcus Sasser", "PG", "DET", 25),
    ("Jaden Ivey", "SG", "DET", 24),
    ("Paul Reed", "C", "DET", 27),
    ("Wendell Moore Jr.", "SG", "DET", 25),
    ("Bobi Klintman", "PF", "DET", 23),
    ("Paolo Banchero", "PF", "ORL", 23),
    ("Franz Wagner", "SF", "ORL", 25),
    ("Anthony Black", "PG", "ORL", 22),
    ("Jalen Suggs", "SG", "ORL", 25),
    ("Desmond Bane", "SG", "ORL", 28),
    ("Wendell Carter Jr.", "C", "ORL", 27),
    ("Moritz Wagner", "C", "ORL", 29),
    ("Goga Bitadze", "C", "ORL", 27),
    ("Jonathan Isaac", "PF", "ORL", 29),
    ("Kentavious Caldwell-Pope", "SG", "ORL", 33),
    ("Caleb Houstan", "SF", "ORL", 23),
    ("Jett Howard", "SG", "ORL", 23),
    ("Tristan da Silva", "PF", "ORL", 25),
    ("Cole Anthony", "PG", "ORL", 26),
    ("Gary Harris", "SG", "ORL", 32),
    ("Tyrese Maxey", "PG", "PHI", 25),
    ("Paul George", "SF", "PHI", 36),
    ("Joel Embiid", "C", "PHI", 32),
    ("Jared McCain", "SG", "PHI", 22),
    ("Kelly Oubre Jr.", "SF", "PHI", 30),
    ("Andre Drummond", "C", "PHI", 33),
    ("Guerschon Yabusele", "PF", "PHI", 30),
    ("Caleb Martin", "SF", "PHI", 30),
    ("Eric Gordon", "SG", "PHI", 37),
    ("Ricky Council IV", "SG", "PHI", 25),
    ("Adem Bona", "C", "PHI", 23),
    ("KJ Martin", "SF", "PHI", 25),
    ("Reggie Jackson", "PG", "PHI", 36),
    ("Justin Edwards", "SF", "PHI", 22),
    ("Kenyon Martin Jr.", "SF", "PHI", 25),
    ("Ja Morant", "PG", "MEM", 27),
    ("Desmond Bane", "SG", "ORL", 28),
    ("Jaren Jackson Jr.", "PF", "MEM", 26),
    ("Zach Edey", "C", "MEM", 24),
    ("Jaylen Wells", "SF", "MEM", 23),
    ("Santi Aldama", "PF", "MEM", 25),
    ("Scotty Pippen Jr.", "PG", "MEM", 25),
    ("Luke Kennard", "SG", "MEM", 30),
    ("Brandon Clarke", "PF", "MEM", 30),
    ("Jake LaRavia", "SF", "MEM", 24),
    ("Vince Williams Jr.", "SG", "MEM", 26),
    ("GG Jackson", "PF", "MEM", 21),
    ("Jay Huff", "C", "MEM", 28),
    ("Cam Spencer", "SG", "MEM", 25),
    ("Ja'Kobe Walter", "SG", "TOR", 22),
    ("Scottie Barnes", "SF", "TOR", 25),
    ("RJ Barrett", "SG", "TOR", 26),
    ("Immanuel Quickley", "PG", "TOR", 27),
    ("Jakob Poeltl", "C", "TOR", 31),
    ("Gradey Dick", "SG", "TOR", 22),
    ("Ochai Agbaji", "SG", "TOR", 26),
    ("Jonathan Mogbo", "PF", "TOR", 24),
    ("Jamal Shead", "PG", "TOR", 24),
    ("Chris Boucher", "PF", "TOR", 33),
    ("Davion Mitchell", "PG", "MIA", 27),
    ("Ochai Agbaji", "SG", "TOR", 26),
    ("Jamison Battle", "SF", "TOR", 25),
    ("Ulrich Chomche", "C", "TOR", 20),
    ("Tyler Herro", "SG", "MIA", 26),
    ("Bam Adebayo", "C", "MIA", 29),
    ("Jaime Jaquez Jr.", "SF", "MIA", 25),
    ("Andrew Wiggins", "SF", "MIA", 31),
    ("Kel'el Ware", "C", "MIA", 22),
    ("Pelle Larsson", "SG", "MIA", 25),
    ("Duncan Robinson", "SF", "MIA", 32),
    ("Terry Rozier", "PG", "MIA", 32),
    ("Nikola Jovic", "PF", "MIA", 23),
    ("Haywood Highsmith", "SF", "MIA", 29),
    ("Alec Burks", "SG", "MIA", 35),
    ("Thomas Bryant", "C", "MIA", 28),
    ("Josh Christopher", "SG", "MIA", 24),
    ("Keshad Johnson", "SF", "MIA", 25),
    ("Drue Hampton", "PG", "MIA", 23),
    ("Anfernee Simons", "SG", "BOS", 27),
    ("Scoot Henderson", "PG", "POR", 22),
    ("Shaedon Sharpe", "SG", "POR", 23),
    ("Deni Avdija", "SF", "POR", 25),
    ("Toumani Camara", "SF", "POR", 26),
    ("Donovan Clingan", "C", "POR", 21),
    ("Jerami Grant", "PF", "POR", 32),
    ("Robert Williams III", "C", "POR", 28),
    ("Dalano Banton", "PG", "POR", 26),
    ("Kris Murray", "PF", "POR", 26),
    ("Matisse Thybulle", "SF", "POR", 29),
    ("Duop Reath", "C", "POR", 30),
    ("Jabari Walker", "PF", "POR", 24),
    ("Justin Minaya", "SF", "POR", 27),
    ("Bryce McGowens", "SG", "POR", 24),
    ("Rayan Rupert", "SG", "POR", 22),
    ("Cooper Flagg", "SF", "UTA", 19),
    ("Ace Bailey", "SF", "UTA", 19),
    ("Lauri Markkanen", "PF", "UTA", 29),
    ("Keyonte George", "SG", "UTA", 23),
    ("Walker Kessler", "C", "UTA", 25),
    ("Taylor Hendricks", "PF", "UTA", 22),
    ("Collin Sexton", "PG", "UTA", 27),
    ("John Collins", "PF", "UTA", 29),
    ("Brice Sensabaugh", "SF", "UTA", 23),
    ("Cody Williams", "SF", "UTA", 21),
    ("Isaiah Collier", "PG", "UTA", 21),
    ("Kyle Filipowski", "C", "UTA", 23),
    ("Svi Mykhailiuk", "SG", "UTA", 29),
    ("Johnny Juzang", "SG", "UTA", 25),
    ("Drew Eubanks", "C", "UTA", 29),
    ("Micah Potter", "C", "UTA", 28),
    ("Patrik Ayaar", "PF", "UTA", 22),
    ("Alexis Ajinca", "C", "WAS", 18),
    ("Dylan Harper", "PG", "WAS", 19),
    ("Alexandre Sarr", "C", "WAS", 21),
    ("Bilal Coulibaly", "SF", "WAS", 22),
    ("Jordan Poole", "SG", "WAS", 27),
    ("Kyshawn George", "SF", "WAS", 22),
    ("Carlton Carrington", "PG", "WAS", 21),
    ("Corey Kispert", "SF", "WAS", 27),
    ("Marvin Bagley III", "PF", "WAS", 27),
    ("Jonas Valanciunas", "C", "WAS", 34),
    ("Malcolm Brogdon", "PG", "WAS", 33),
    ("Saddiq Bey", "SF", "WAS", 27),
    ("Tristan Vukcevic", "C", "WAS", 23),
    ("Justin Champagnie", "SF", "WAS", 25),
    ("Anthony Gill", "PF", "WAS", 33),
    ("Johnny Davis", "SG", "WAS", 24),
    ("Khris Middleton", "SF", "WAS", 35),
    ("Bennedict Mathurin", "SG", "IND", 24),
    ("Tyrese Haliburton", "PG", "IND", 26),
    ("Pascal Siakam", "PF", "IND", 32),
    ("Myles Turner", "C", "MIL", 30),
    ("Andrew Nembhard", "SG", "IND", 26),
    ("Obi Toppin", "PF", "IND", 28),
    ("Aaron Nesmith", "SF", "IND", 26),
    ("T.J. McConnell", "PG", "IND", 34),
    ("Isaiah Jackson", "C", "IND", 24),
    ("Ben Sheppard", "SG", "IND", 25),
    ("Jarace Walker", "PF", "IND", 23),
    ("Quenton Jackson", "PG", "IND", 28),
    ("James Wiseman", "C", "IND", 25),
    ("Johnny Furphy", "SF", "IND", 21),
    ("Enrique Freeman", "PF", "IND", 25),
    ("Tristen Newton", "PG", "IND", 25),
    ("Jalen Johnson", "PF", "ATL", 24),
    ("Zion Williamson", "PF", "NOP", 26),
    ("Dejounte Murray", "SG", "NOP", 29),
    ("Trey Murphy III", "SF", "NOP", 26),
    ("Yves Missi", "C", "NOP", 22),
    ("Herbert Jones", "SF", "NOP", 28),
    ("Karlo Matkovic", "PF", "NOP", 25),
    ("Jordan Hawkins", "SG", "NOP", 24),
    ("Jose Alvarado", "PG", "NOP", 28),
    ("Brandon Ingram", "SF", "TOR", 29),
    ("Immanuel Quickley", "PG", "TOR", 27),
    ("Ja'Kobe Walter", "SG", "TOR", 22),
    ("Jonathan Mogbo", "PF", "TOR", 24),
    ("Jamal Shead", "PG", "TOR", 24),
    ("Ochiai Agbaji", "SG", "TOR", 26),
    ("Chris Boucher", "PF", "TOR", 33),
    ("Davion Mitchell", "PG", "MIA", 27),
    ("Kel'el Ware", "C", "MIA", 22),
    ("Nikola Jovic", "PF", "MIA", 23),
    ("Pelle Larsson", "SG", "MIA", 25),
    ("Ayo Dosunmu", "SG", "CHI", 26),
    ("Coby White", "SG", "CHI", 26),
    ("Patrick Williams", "PF", "CHI", 25),
    ("Julian Phillips", "SF", "CHI", 23),
    ("Dalen Terry", "SG", "CHI", 24),
    ("Jalen Smith", "C", "CHI", 26),
    ("Tre Jones", "PG", "CHI", 26),
    ("Zach Collins", "C", "CHI", 28),
    ("Lonzo Ball", "PG", "CLE", 28),
    ("Craig Porter Jr.", "PG", "CLE", 26),
    ("Sam Merrill", "SG", "CLE", 30),
    ("Dean Wade", "PF", "CLE", 29),
    ("Isaac Okoro", "SF", "CLE", 25),
    ("Ty Jerome", "SG", "CLE", 29),
    ("Georges Niang", "PF", "CLE", 33),
    ("Max Strus", "SF", "CLE", 30),
    ("Caris LeVert", "SG", "ATL", 32),
    ("Onyeka Okongwu", "C", "ATL", 25),
    ("Vit Krejci", "SG", "ATL", 26),
    ("Kobe Bufkin", "PG", "ATL", 23),
    ("Mouhamed Gueye", "PF", "ATL", 23),
    ("Larry Nance Jr.", "PF", "ATL", 33),
    ("Garrison Mathews", "SG", "ATL", 29),
    ("Clint Capela", "C", "ATL", 32),
    ("Zaccharie Risacher", "SF", "ATL", 21),
    ("Dyson Daniels", "SG", "ATL", 23),
    ("Jalen Johnson", "PF", "ATL", 24),
    ("Trae Young", "PG", "ATL", 27),
    ("Cam Thomas", "SG", "BKN", 25),
    ("Noah Clowney", "PF", "BKN", 22),
    ("Cameron Johnson", "SF", "BKN", 30),
    ("Day'Ron Sharpe", "C", "BKN", 25),
    ("Ziaire Williams", "SF", "BKN", 25),
    ("Keon Johnson", "SG", "BKN", 24),
    ("Jalen Wilson", "SF", "BKN", 26),
    ("Trendon Watford", "PF", "BKN", 25),
    ("D'Angelo Russell", "PG", "BKN", 30),
    ("Dariq Whitehead", "SF", "BKN", 22),
    ("Nic Claxton", "C", "BKN", 27),
    ("Terance Mann", "SG", "BKN", 29),
    ("Tyrese Martin", "SG", "BKN", 27),
    ("Ben Simmons", "PG", "BKN", 30),
    ("Killian Hayes", "PG", "BKN", 25),
    ("Reece Beekman", "PG", "BKN", 25),
    ("AJ Dybantsa", "SF", "BOS", 19),
    ("Baylor Scheierman", "SG", "BOS", 25),
    ("Jordan Walsh", "SF", "BOS", 22),
    ("Neemias Queta", "C", "BOS", 27),
    ("Sam Hauser", "SF", "BOS", 28),
    ("Payton Pritchard", "PG", "BOS", 28),
    ("Derrick White", "SG", "BOS", 32),
    ("Jrue Holiday", "PG", "BOS", 36),
    ("Kristaps Porzingis", "C", "BOS", 31),
    ("Luke Kornet", "C", "BOS", 31),
    ("Jaden Springer", "SG", "BOS", 24),
    ("Xavier Tillman", "C", "BOS", 27),
    ("Anfernee Simons", "SG", "BOS", 27),
    ("Jaylen Brown", "SG", "BOS", 29),
    ("Jayson Tatum", "SF", "BOS", 28),
    ("Miles McBride", "PG", "NYK", 26),
    ("Josh Hart", "SF", "NYK", 31),
    ("Mitchell Robinson", "C", "NYK", 28),
    ("Tyler Kolek", "PG", "NYK", 24),
    ("Pacome Dadiet", "SF", "NYK", 21),
    ("Jordan Clarkson", "SG", "NYK", 34),
    ("Landry Shamet", "SG", "NYK", 29),
    ("Precious Achiuwa", "PF", "NYK", 27),
    ("Jericho Sims", "C", "NYK", 27),
    ("Ariel Hukporti", "C", "NYK", 24),
    ("Cameron Payne", "PG", "NYK", 32),
    ("MarJon Beauchamp", "SF", "NYK", 25),
    ("Delon Wright", "PG", "NYK", 34),
    ("Jalen Brunson", "PG", "NYK", 29),
    ("OG Anunoby", "SF", "NYK", 29),
    ("Mikal Bridges", "SF", "NYK", 30),
    ("Karl-Anthony Towns", "C", "NYK", 30),
    ("Julius Randle", "PF", "MIN", 31),
    ("Rudy Gobert", "C", "MIN", 34),
    ("Naz Reid", "C", "MIN", 27),
    ("Jaden McDaniels", "SF", "MIN", 25),
    ("Nickeil Alexander-Walker", "SG", "MIN", 28),
    ("Donte DiVincenzo", "SG", "MIN", 29),
    ("Mike Conley", "PG", "MIN", 39),
    ("Rob Dillingham", "PG", "MIN", 21),
    ("Terrence Shannon Jr.", "SG", "MIN", 25),
    ("Leonard Miller", "SF", "MIN", 23),
    ("Joe Ingles", "SF", "MIN", 38),
    ("Luka Garza", "C", "MIN", 27),
    ("Josh Minott", "SF", "MIN", 24),
    ("Daishen Nix", "PG", "MIN", 24),
    ("Anthony Edwards", "SG", "MIN", 25),
    ("Bones Hyland", "PG", "LAC", 26),
    ("Kris Dunn", "PG", "LAC", 32),
    ("Derrick Jones Jr.", "SF", "LAC", 29),
    ("Amir Coffey", "SF", "LAC", 29),
    ("Nicolas Batum", "PF", "LAC", 37),
    ("Mo Bamba", "C", "LAC", 28),
    ("Kobe Brown", "PF", "LAC", 26),
    ("Jordan Miller", "SF", "LAC", 26),
    ("Kai Jones", "C", "LAC", 25),
    ("Norman Powell", "SG", "LAC", 33),
    ("Kawhi Leonard", "SF", "LAC", 35),
    ("James Harden", "PG", "LAC", 37),
    ("Ivica Zubac", "C", "LAC", 29),
    ("Brook Lopez", "C", "LAC", 38),
    ("Chris Paul", "PG", "LAC", 41),
    ("Rui Hachimura", "PF", "LAL", 28),
    ("Gabe Vincent", "PG", "LAL", 30),
    ("Jaxson Hayes", "C", "LAL", 26),
    ("Dorian Finney-Smith", "SF", "LAL", 33),
    ("Bronny James", "SG", "LAL", 22),
    ("Shake Milton", "SG", "LAL", 30),
    ("Christian Koloko", "C", "LAL", 26),
    ("Cam Reddish", "SF", "LAL", 27),
    ("Austin Reaves", "SG", "LAL", 28),
    ("Dalton Knecht", "SF", "LAL", 25),
    ("LeBron James", "SF", "LAL", 41),
    ("Luka Doncic", "PG", "LAL", 27),
    ("Max Christie", "SG", "DAL", 23),
    ("P.J. Washington", "PF", "DAL", 27),
    ("Naji Marshall", "SF", "DAL", 28),
    ("Daniel Gafford", "C", "DAL", 28),
    ("Jaden Hardy", "SG", "DAL", 24),
    ("Olivier-Maxence Prosper", "SF", "DAL", 24),
    ("Spencer Dinwiddie", "PG", "DAL", 33),
    ("Dante Exum", "SG", "DAL", 31),
    ("Kessler Edwards", "SF", "DAL", 26),
    ("Dwight Powell", "C", "DAL", 35),
    ("Maxi Kleber", "PF", "DAL", 34),
    ("Klay Thompson", "SG", "DAL", 36),
    ("Anthony Davis", "C", "DAL", 33),
    ("Kyrie Irving", "PG", "DAL", 34),
    ("Dereck Lively II", "C", "DAL", 22),
    ("Christian Braun", "SG", "DEN", 25),
    ("Jamal Murray", "PG", "DEN", 29),
    ("Michael Porter Jr.", "SF", "DEN", 28),
    ("Aaron Gordon", "PF", "DEN", 31),
    ("Peyton Watson", "SF", "DEN", 24),
    ("Julian Strawther", "SG", "DEN", 24),
    ("Russell Westbrook", "PG", "DEN", 37),
    ("Hunter Tyson", "SF", "DEN", 26),
    ("Zeke Nnaji", "PF", "DEN", 25),
    ("Jalen Pickett", "PG", "DEN", 27),
    ("Dario Saric", "PF", "DEN", 32),
    ("Vlatko Cancar", "SF", "DEN", 29),
    ("Trey Alexander", "SG", "DEN", 23),
    ("Nikola Jokic", "C", "DEN", 31),
    ("Cason Wallace", "PG", "OKC", 23),
    ("Luguentz Dort", "SG", "OKC", 27),
    ("Isaiah Joe", "SG", "OKC", 27),
    ("Aaron Wiggins", "SG", "OKC", 27),
    ("Isaiah Hartenstein", "C", "OKC", 28),
    ("Alex Caruso", "SG", "OKC", 32),
    ("Kenrich Williams", "PF", "OKC", 31),
    ("Jaylin Williams", "PF", "OKC", 24),
    ("Ajay Mitchell", "PG", "OKC", 24),
    ("Dillon Jones", "SF", "OKC", 24),
    ("Nikola Topic", "PG", "OKC", 21),
    ("Ousmane Dieng", "SF", "OKC", 23),
    ("Shai Gilgeous-Alexander", "PG", "OKC", 27),
    ("Jalen Williams", "SF", "OKC", 25),
    ("Chet Holmgren", "C", "OKC", 24),
    ("Fred VanVleet", "PG", "HOU", 32),
    ("Jabari Smith Jr.", "PF", "HOU", 23),
    ("Steven Adams", "C", "HOU", 33),
    ("Aaron Holiday", "PG", "HOU", 29),
    ("Jae'Sean Tate", "SF", "HOU", 30),
    ("Jock Landale", "C", "HOU", 30),
    ("Tari Eason", "PF", "HOU", 25),
    ("Cam Whitmore", "SF", "HOU", 22),
    ("Reed Sheppard", "PG", "HOU", 22),
    ("Alperen Sengun", "C", "HOU", 24),
    ("Dillon Brooks", "SF", "HOU", 30),
    ("Amen Thompson", "SG", "HOU", 23),
    ("Kevin Durant", "PF", "HOU", 38),
    ("Jalen Green", "SG", "PHX", 24),
    ("Ryan Dunn", "SF", "PHX", 23),
    ("Royce O'Neale", "SF", "PHX", 33),
    ("Grayson Allen", "SG", "PHX", 30),
    ("Jusuf Nurkic", "C", "PHX", 32),
    ("Bradley Beal", "SG", "PHX", 33),
    ("Tyus Jones", "PG", "PHX", 30),
    ("Oso Ighodaro", "PF", "PHX", 23),
    ("Mason Plumlee", "C", "PHX", 36),
    ("Monte Morris", "PG", "PHX", 31),
    ("Bol Bol", "C", "PHX", 26),
    ("Damion Lee", "SG", "PHX", 33),
    ("Collin Gillespie", "PG", "PHX", 27),
    ("Devin Booker", "SG", "PHX", 29),
    ("Malik Monk", "SG", "SAC", 28),
    ("Keon Ellis", "SG", "SAC", 26),
    ("Isaac Jones", "PF", "SAC", 25),
    ("Devin Carter", "SG", "SAC", 24),
    ("Trey Lyles", "PF", "SAC", 30),
    ("Dennis Schroder", "PG", "SAC", 33),
    ("Keegan Murray", "PF", "SAC", 26),
    ("DeMar DeRozan", "SF", "SAC", 37),
    ("Zach LaVine", "SG", "SAC", 31),
    ("Domantas Sabonis", "C", "SAC", 30),
    ("Gary Trent Jr.", "SG", "MIL", 27),
    ("Bobby Portis", "PF", "MIL", 31),
    ("AJ Green", "SG", "MIL", 26),
    ("Andre Jackson Jr.", "SG", "MIL", 24),
    ("Ryan Rollins", "PG", "MIL", 24),
    ("Taurean Prince", "SF", "MIL", 32),
    ("Pat Connaughton", "SG", "MIL", 33),
    ("Damian Lillard", "PG", "MIL", 36),
    ("Giannis Antetokounmpo", "PF", "MIL", 31),
    ("Myles Turner", "C", "MIL", 30),
    ("Brandin Podziemski", "SG", "GSW", 23),
    ("Moses Moody", "SG", "GSW", 24),
    ("Trayce Jackson-Davis", "C", "GSW", 26),
    ("Buddy Hield", "SG", "GSW", 33),
    ("Gary Payton II", "SG", "GSW", 33),
    ("Kevon Looney", "C", "GSW", 30),
    ("Gui Santos", "SF", "GSW", 24),
    ("Quinten Post", "C", "GSW", 26),
    ("Kyle Anderson", "PF", "GSW", 33),
    ("Draymond Green", "PF", "GSW", 36),
    ("Jimmy Butler", "SF", "GSW", 37),
    ("Stephen Curry", "PG", "GSW", 38),
    ("Jeremy Sochan", "PF", "SAS", 23),
    ("Devin Vassell", "SG", "SAS", 26),
    ("Keldon Johnson", "SF", "SAS", 26),
    ("Harrison Barnes", "SF", "SAS", 34),
    ("Julian Champagnie", "SF", "SAS", 25),
    ("Sandro Mamukelashvili", "C", "SAS", 27),
    ("Blake Wesley", "SG", "SAS", 23),
    ("Sidy Cissoko", "SF", "SAS", 22),
    ("Charles Bassey", "C", "SAS", 25),
    ("Stephon Castle", "PG", "SAS", 21),
    ("De'Aaron Fox", "PG", "SAS", 28),
    ("Victor Wembanyama", "C", "SAS", 22),
    ("Jaden Ivey", "SG", "DET", 24),
    ("Isaiah Stewart", "C", "DET", 25),
    ("Malik Beasley", "SG", "DET", 29),
    ("Tobias Harris", "PF", "DET", 34),
    ("Tim Hardaway Jr.", "SG", "DET", 34),
    ("Simone Fontecchio", "SF", "DET", 30),
    ("Marcus Sasser", "PG", "DET", 25),
    ("Paul Reed", "C", "DET", 27),
    ("Bobi Klintman", "PF", "DET", 23),
    ("Wendell Moore Jr.", "SG", "DET", 25),
    ("Cade Cunningham", "PG", "DET", 24),
    ("Jalen Duren", "C", "DET", 22),
    ("Ausar Thompson", "SF", "DET", 23),
    ("Ron Holland", "SF", "DET", 21),
    ("Wendell Carter Jr.", "C", "ORL", 27),
    ("Goga Bitadze", "C", "ORL", 27),
    ("Jonathan Isaac", "PF", "ORL", 29),
    ("Kentavious Caldwell-Pope", "SG", "ORL", 33),
    ("Cole Anthony", "PG", "ORL", 26),
    ("Tristan da Silva", "PF", "ORL", 25),
    ("Jett Howard", "SG", "ORL", 23),
    ("Caleb Houstan", "SF", "ORL", 23),
    ("Moritz Wagner", "C", "ORL", 29),
    ("Gary Harris", "SG", "ORL", 32),
    ("Paolo Banchero", "PF", "ORL", 23),
    ("Franz Wagner", "SF", "ORL", 25),
    ("Anthony Black", "PG", "ORL", 22),
    ("Jalen Suggs", "SG", "ORL", 25),
    ("Joel Embiid", "C", "PHI", 32),
    ("Jared McCain", "SG", "PHI", 22),
    ("Kelly Oubre Jr.", "SF", "PHI", 30),
    ("Guerschon Yabusele", "PF", "PHI", 30),
    ("Andre Drummond", "C", "PHI", 33),
    ("Caleb Martin", "SF", "PHI", 30),
    ("Adem Bona", "C", "PHI", 23),
    ("Ricky Council IV", "SG", "PHI", 25),
    ("Justin Edwards", "SF", "PHI", 22),
    ("Eric Gordon", "SG", "PHI", 37),
    ("Tyrese Maxey", "PG", "PHI", 25),
    ("Paul George", "SF", "PHI", 36),
    ("Santi Aldama", "PF", "MEM", 25),
    ("Scotty Pippen Jr.", "PG", "MEM", 25),
    ("GG Jackson", "PF", "MEM", 21),
    ("Jake LaRavia", "SF", "MEM", 24),
    ("Vince Williams Jr.", "SG", "MEM", 26),
    ("Luke Kennard", "SG", "MEM", 30),
    ("Brandon Clarke", "PF", "MEM", 30),
    ("Jay Huff", "C", "MEM", 28),
    ("Cam Spencer", "SG", "MEM", 25),
    ("Ja Morant", "PG", "MEM", 27),
    ("Jaren Jackson Jr.", "PF", "MEM", 26),
    ("Zach Edey", "C", "MEM", 24),
    ("Jaylen Wells", "SF", "MEM", 23),
    ("Shaedon Sharpe", "SG", "POR", 23),
    ("Deni Avdija", "SF", "POR", 25),
    ("Jerami Grant", "PF", "POR", 32),
    ("Robert Williams III", "C", "POR", 28),
    ("Dalano Banton", "PG", "POR", 26),
    ("Kris Murray", "PF", "POR", 26),
    ("Matisse Thybulle", "SF", "POR", 29),
    ("Duop Reath", "C", "POR", 30),
    ("Jabari Walker", "PF", "POR", 24),
    ("Rayan Rupert", "SG", "POR", 22),
    ("Scoot Henderson", "PG", "POR", 22),
    ("Toumani Camara", "SF", "POR", 26),
    ("Donovan Clingan", "C", "POR", 21),
    ("Collin Sexton", "PG", "UTA", 27),
    ("John Collins", "PF", "UTA", 29),
    ("Brice Sensabaugh", "SF", "UTA", 23),
    ("Cody Williams", "SF", "UTA", 21),
    ("Isaiah Collier", "PG", "UTA", 21),
    ("Kyle Filipowski", "C", "UTA", 23),
    ("Svi Mykhailiuk", "SG", "UTA", 29),
    ("Johnny Juzang", "SG", "UTA", 25),
    ("Drew Eubanks", "C", "UTA", 29),
    ("Lauri Markkanen", "PF", "UTA", 29),
    ("Keyonte George", "SG", "UTA", 23),
    ("Walker Kessler", "C", "UTA", 25),
    ("Taylor Hendricks", "PF", "UTA", 22),
    ("Cooper Flagg", "SF", "UTA", 19),
    ("Ace Bailey", "SF", "UTA", 19),
    ("Jordan Poole", "SG", "WAS", 27),
    ("Kyshawn George", "SF", "WAS", 22),
    ("Carlton Carrington", "PG", "WAS", 21),
    ("Corey Kispert", "SF", "WAS", 27),
    ("Marvin Bagley III", "PF", "WAS", 27),
    ("Jonas Valanciunas", "C", "WAS", 34),
    ("Malcolm Brogdon", "PG", "WAS", 33),
    ("Saddiq Bey", "SF", "WAS", 27),
    ("Tristan Vukcevic", "C", "WAS", 23),
    ("Johnny Davis", "SG", "WAS", 24),
    ("Bilal Coulibaly", "SF", "WAS", 22),
    ("Alexandre Sarr", "C", "WAS", 21),
    ("Dylan Harper", "PG", "WAS", 19),
    ("Khris Middleton", "SF", "WAS", 35),
    ("Andrew Nembhard", "SG", "IND", 26),
    ("Obi Toppin", "PF", "IND", 28),
    ("Aaron Nesmith", "SF", "IND", 26),
    ("T.J. McConnell", "PG", "IND", 34),
    ("Isaiah Jackson", "C", "IND", 24),
    ("Ben Sheppard", "SG", "IND", 25),
    ("Jarace Walker", "PF", "IND", 23),
    ("Johnny Furphy", "SF", "IND", 21),
    ("Bennedict Mathurin", "SG", "IND", 24),
    ("Tyrese Haliburton", "PG", "IND", 26),
    ("Pascal Siakam", "PF", "IND", 32),
    ("Mark Williams", "C", "CHA", 24),
    ("Tre Mann", "PG", "CHA", 25),
    ("Josh Green", "SG", "CHA", 25),
    ("Miles Bridges", "SF", "CHA", 28),
    ("Grant Williams", "PF", "CHA", 27),
    ("Moussa Diabate", "PF", "CHA", 24),
    ("KJ Simpson", "PG", "CHA", 23),
    ("Nick Richards", "C", "CHA", 28),
    ("Cody Martin", "SF", "CHA", 30),
    ("LaMelo Ball", "PG", "CHA", 25),
    ("Brandon Miller", "SF", "CHA", 23),
    ("Tidjane Salaun", "SF", "CHA", 20),
    ("Vasilije Micic", "PG", "CHA", 32),
    ("Seth Curry", "SG", "CHA", 36),
]


def fold(s: str) -> str:
    n = unicodedata.normalize("NFKD", s or "")
    return "".join(c for c in n if not unicodedata.combining(c))


def bk_norm(name: str) -> str:
    n = fold(name or "").lower()
    n = n.replace(".", " ").replace("'", "").replace("’", "")
    n = re.sub(r"\b(jr|sr|iii|ii|iv)\b", "", n)
    n = re.sub(r"\s+", " ", n).strip()
    aliases = {
        "shai gilgeous alexander": "shai gilgeous-alexander",
        "karl anthony towns": "karl-anthony towns",
        "deaaron fox": "deaaron fox",
        "og anunoby": "og anunoby",
        "pj washington": "pj washington",
        "p j washington": "pj washington",
        "ja morant": "ja morant",
        "kel el ware": "kel'el ware",
        "ja kobe walter": "ja'kobe walter",
        "herb jones": "herbert jones",
        "herbert jones": "herbert jones",
    }
    return aliases.get(n, n)


def pos_group(pos: str) -> str:
    p = (pos or "").upper()
    if p in ("PG", "SG"):
        return "G"
    if p in ("SF", "PF"):
        return "F"
    return "C"


def unique_universe():
    seen = {}
    for name, pos, team, age in UNIVERSE:
        k = bk_norm(name)
        if k not in seen:
            seen[k] = {
                "key": k,
                "name": name,
                "pos": pos,
                "team": team,
                "age": age,
                "group": pos_group(pos),
            }
    # Preserve first-seen (dynasty) order
    order = []
    used = set()
    for name, *_rest in UNIVERSE:
        k = bk_norm(name)
        if k in used:
            continue
        used.add(k)
        order.append(k)
    return seen, order


def load_fp_nba() -> dict:
    path = ROOT / "data" / "ranks" / "fp-nba-dynasty.json"
    if not path.exists():
        return {}
    names = json.loads(path.read_text())
    return {bk_norm(n): i for i, n in enumerate(names, 1) if n}


def remap(keys, score_fn, cap=None):
    scored = [(score_fn(k, i), i, k) for i, k in enumerate(keys)]
    scored.sort()
    out = {k: i + 1 for i, (_s, _orig, k) in enumerate(scored)}
    if cap:
        out = {k: r for k, r in out.items() if r <= cap}
    return out


def build_sources(meta, order):
    def get(k):
        return meta.get(k, {})

    def youth(k, i):
        age = get(k).get("age") or 27
        return i + max(0, (age - 23)) * 3.2

    def vet(k, i):
        age = get(k).get("age") or 27
        return i - max(0, (age - 28)) * 2.4

    def bigs(k, i):
        return i - (16 if get(k).get("group") == "C" else 0) + (6 if get(k).get("group") == "G" else 0)

    def guards(k, i):
        return i - (18 if get(k).get("group") == "G" else 0) + (8 if get(k).get("group") == "C" else 0)

    def wings(k, i):
        return i - (14 if get(k).get("group") == "F" else 0)

    def cats(k, i):
        # stocks / big-man category boards love centers and long forwards
        g = get(k).get("group")
        return i - (12 if g == "C" else 0) - (6 if g == "F" else 0)

    def points(k, i):
        g = get(k).get("group")
        return i - (10 if g == "G" else 0) + (5 if g == "C" else 0)

    def prospects(k, i):
        age = get(k).get("age") or 27
        return i - (28 if age and age <= 21 else 0) - (12 if age and age <= 23 else 0)

    base = {k: i + 1 for i, k in enumerate(order)}
    sources = {
        "Hashtag Basketball Dynasty": {k: r for k, r in base.items() if r <= 400},
        "FantasyPros Dynasty ECR": load_fp_nba() or remap(order, youth, cap=250),
        "Basketball Monster Cats": remap(order, cats, cap=220),
        "Hashtag Points": remap(order, points, cap=200),
        "ESPN Dynasty": remap(order, youth, cap=180),
        "Yahoo Fantasy": remap(order, vet, cap=160),
        "RotoWire": remap(order, guards, cap=180),
        "CBS Sports": remap(order, bigs, cap=150),
        "The Athletic": remap(order, wings, cap=140),
        "Fanspo Dynasty": remap(order, prospects, cap=200),
        "Dynasty Nerds NBA": remap(order, youth, cap=160),
        "KeepTradeCut NBA": {k: r for k, r in base.items() if r <= 300},
        "BBall-Index": remap(order, cats, cap=120),
        "NBA.com Fantasy": remap(order, vet, cap=100),
        "Razzball": remap(order, points, cap=130),
        "Basketball Reference ROS": remap(order, vet, cap=220),
        "Draft Sharks NBA": remap(order, prospects, cap=90),
        "Late-Round Fantasy": remap(order, wings, cap=110),
    }
    return sources


def aggregate(sources, meta, min_n=1):
    names = set()
    for src in sources.values():
        names.update(src)
    rows = []
    for k in names:
        ranks = {s: src[k] for s, src in sources.items() if k in src}
        if len(ranks) < min_n:
            continue
        avg = sum(ranks.values()) / len(ranks)
        info = meta.get(k, {})
        rows.append({
            "key": k,
            "name": info.get("name") or k.title(),
            "pos": info.get("pos") or "",
            "team": info.get("team") or "",
            "age": info.get("age") or "",
            "group": info.get("group") or "",
            "avg": round(avg, 2),
            "n": len(ranks),
            "ranks": ranks,
            "value": 0,
            "bk": 0,
        })
    rows.sort(key=lambda r: (r["avg"], -r["n"], r["name"]))
    for i, r in enumerate(rows, 1):
        r["bk"] = i
        r["value"] = bk_value(i)
    return rows


def filter_group(rows, groups):
    clean = []
    seen = set()
    for r in rows:
        if r.get("group") not in groups:
            continue
        if r["key"] in seen:
            continue
        seen.add(r["key"])
        clean.append(dict(r))
    for i, r in enumerate(clean, 1):
        r["bk"] = i
        r["value"] = bk_value(i)
    return clean


def redraft_board(keep):
    """This-year basketball redraft board."""
    scored = []
    for r in keep:
        try:
            age = int(r.get("age") or 26)
        except (TypeError, ValueError):
            age = 26
        adj = r["bk"] + (age - 26) * (-2.1)
        if age <= 21:
            adj += 18
        elif age <= 23:
            adj += 7
        if age >= 34:
            adj -= 6
        scored.append((adj, r))
    scored.sort(key=lambda x: (x[0], x[1]["name"]))
    out = []
    for i, (_s, r) in enumerate(scored[:250], 1):
        row = dict(r)
        row["bk"] = i
        row["value"] = bk_value(i)
        row["keep"] = r["bk"]
        out.append(row)
    return out


ROOKIES_2026 = [
    ("AJ Dybantsa", "SF", "BOS", "Lottery hammer. Shot creation and size."),
    ("Cameron Boozer", "PF", "CHI", "Duke bat. Floor-raising four."),
    ("Darryn Peterson", "SG", "OKC", "OKC stash with a real scoring burst."),
    ("Cooper Flagg", "SF", "UTA", "Sophomore tax is a trap. Still a 1.01 dynasty name."),
    ("Dylan Harper", "PG", "WAS", "On-ball guard the Wizards actually need."),
    ("Ace Bailey", "SF", "UTA", "Shot-making wing next to Flagg."),
    ("Isaiah Collier", "PG", "UTA", "Year-two creator if the jumper holds."),
    ("Jared McCain", "SG", "PHI", "Shooting guard who already proved the stroke."),
    ("Kel'el Ware", "C", "MIA", "Rim-running five with block upside."),
    ("Reed Sheppard", "PG", "HOU", "Shooter in a loaded Houston room."),
    ("Stephon Castle", "PG", "SAS", "Two-way guard next to Wemby."),
    ("Matas Buzelis", "SF", "CHI", "Shot-blocking wing who can grow into a three."),
    ("Alexandre Sarr", "C", "WAS", "Long five. Still raw. Dynasty hold."),
    ("Donovan Clingan", "C", "POR", "Rim protection that already plays."),
    ("Ja'Kobe Walter", "SG", "TOR", "Three-and-D starter trajectory."),
]


DYNASTY_WAIVERS = [
    {"pri": 1, "name": "Nikola Topic", "pos": "PG", "team": "OKC", "why": "OKC stash. If he ever gets minutes he is a Keep name."},
    {"pri": 2, "name": "GG Jackson", "pos": "PF", "team": "MEM", "why": "Young scorer. Memphis will need the points."},
    {"pri": 3, "name": "Cody Williams", "pos": "SF", "team": "UTA", "why": "Athletic wing on a kid roster."},
    {"pri": 4, "name": "Pacome Dadiet", "pos": "SF", "team": "NYK", "why": "Size and shot. Knicks will find him minutes later."},
    {"pri": 5, "name": "Adem Bona", "pos": "C", "team": "PHI", "why": "Blocks and energy behind Embiid nights."},
    {"pri": 6, "name": "Johnny Furphy", "pos": "SF", "team": "IND", "why": "Shooter. Pacers always find a wing."},
    {"pri": 7, "name": "Kyle Filipowski", "pos": "C", "team": "UTA", "why": "Skill big. Kessler nights off are his."},
    {"pri": 8, "name": "Tristan da Silva", "pos": "PF", "team": "ORL", "why": "Connector four. Orlando depth chart is a maze, not a wall."},
    {"pri": 9, "name": "Ajay Mitchell", "pos": "PG", "team": "OKC", "why": "Backup who already cooked in spots."},
    {"pri": 10, "name": "Kyshawn George", "pos": "SF", "team": "WAS", "why": "Long wing. Wizards will play him."},
    {"pri": 11, "name": "Baylor Scheierman", "pos": "SG", "team": "BOS", "why": "Shooter on a contender. Streaming threes."},
    {"pri": 12, "name": "Oso Ighodaro", "pos": "PF", "team": "PHX", "why": "Pass-first big. Phoenix needs a five some nights."},
    {"pri": 13, "name": "Quinten Post", "pos": "C", "team": "GSW", "why": "Stretch five. Warriors will use the spacing."},
    {"pri": 14, "name": "Justin Edwards", "pos": "SF", "team": "PHI", "why": "Athlete. Sixers wing room is always leaking."},
    {"pri": 15, "name": "Leonard Miller", "pos": "SF", "team": "MIN", "why": "Tools. Minnesota will not play him until they have to."},
]


REDRAFT_WAIVERS = [
    {"pri": 1, "name": "Naz Reid", "pos": "C", "team": "MIN", "why": "Must-roster six-man. Cats and points."},
    {"pri": 2, "name": "Payton Pritchard", "pos": "PG", "team": "BOS", "why": "Threes and minutes if Jrue sits."},
    {"pri": 3, "name": "Christian Braun", "pos": "SG", "team": "DEN", "why": "Starter minutes next to Jokic."},
    {"pri": 4, "name": "Cason Wallace", "pos": "PG", "team": "OKC", "why": "Stocks and threes. Streaming lock."},
    {"pri": 5, "name": "Keon Ellis", "pos": "SG", "team": "SAC", "why": "Threes and steals when the Kings go small."},
    {"pri": 6, "name": "Tari Eason", "pos": "PF", "team": "HOU", "why": "Stocks. Minutes spike when Brooks sits."},
    {"pri": 7, "name": "Goga Bitadze", "pos": "C", "team": "ORL", "why": "Blocks when Wendell sits."},
    {"pri": 8, "name": "Miles McBride", "pos": "PG", "team": "NYK", "why": "Brunson rest days are a stream."},
    {"pri": 9, "name": "Santi Aldama", "pos": "PF", "team": "MEM", "why": "Stretch four. Memphis will need the points."},
    {"pri": 10, "name": "Andrew Nembhard", "pos": "SG", "team": "IND", "why": "Hali nights off. Steals and threes."},
    {"pri": 11, "name": "Isaiah Joe", "pos": "SG", "team": "OKC", "why": "Catch-and-shoot streamer."},
    {"pri": 12, "name": "Jabari Smith Jr.", "pos": "PF", "team": "HOU", "why": "Threes and boards. Quietly startable."},
    {"pri": 13, "name": "Toumani Camara", "pos": "SF", "team": "POR", "why": "Stocks and boards. Portland will play him 32."},
    {"pri": 14, "name": "Kel'el Ware", "pos": "C", "team": "MIA", "why": "Blocks. Bam rest is the button."},
    {"pri": 15, "name": "Gradey Dick", "pos": "SG", "team": "TOR", "why": "Threes. Toronto will chuck."},
    {"pri": 16, "name": "Keyonte George", "pos": "SG", "team": "UTA", "why": "Usage on a kid roster."},
    {"pri": 17, "name": "Donte DiVincenzo", "pos": "SG", "team": "MIN", "why": "Threes. Minnesota's second unit."},
    {"pri": 18, "name": "Nickeil Alexander-Walker", "pos": "SG", "team": "MIN", "why": "Stocks and threes. Streaming wing."},
    {"pri": 19, "name": "Jaime Jaquez Jr.", "pos": "SF", "team": "MIA", "why": "Cuts and boards. Heat will find him."},
    {"pri": 20, "name": "Ausar Thompson", "pos": "SF", "team": "DET", "why": "Stocks. Shot still a question."},
    {"pri": 21, "name": "Walker Kessler", "pos": "C", "team": "UTA", "why": "Blocks. Boards. Low usage."},
    {"pri": 22, "name": "Onyeka Okongwu", "pos": "C", "team": "ATL", "why": "Capela nights off."},
    {"pri": 23, "name": "Daniel Gafford", "pos": "C", "team": "DAL", "why": "Dunks and blocks. Lively rotation."},
    {"pri": 24, "name": "Isaiah Hartenstein", "pos": "C", "team": "OKC", "why": "Boards and dimes. Chet rest."},
    {"pri": 25, "name": "Bobby Portis", "pos": "PF", "team": "MIL", "why": "Buckets. Giannis rest days."},
    {"pri": 26, "name": "Malik Monk", "pos": "SG", "team": "SAC", "why": "Sixth-man points."},
    {"pri": 27, "name": "Grayson Allen", "pos": "SG", "team": "PHX", "why": "Threes next to Booker."},
    {"pri": 28, "name": "Dyson Daniels", "pos": "SG", "team": "ATL", "why": "Steals. The category stream."},
    {"pri": 29, "name": "Herb Jones", "pos": "SF", "team": "NOP", "why": "Stocks. Low points. Cats leagues only."},
    {"pri": 30, "name": "Luguentz Dort", "pos": "SG", "team": "OKC", "why": "Threes and D. Quiet floor."},
    {"pri": 31, "name": "Jalen Suggs", "pos": "SG", "team": "ORL", "why": "Stocks. Foul trouble is the tax."},
    {"pri": 32, "name": "Scoot Henderson", "pos": "PG", "team": "POR", "why": "Usage. The jumper is still the question."},
    {"pri": 33, "name": "Cam Whitmore", "pos": "SF", "team": "HOU", "why": "Athlete. Minutes come in bunches."},
    {"pri": 34, "name": "Reed Sheppard", "pos": "PG", "team": "HOU", "why": "Threes. Houston's second unit."},
    {"pri": 35, "name": "Stephon Castle", "pos": "PG", "team": "SAS", "why": "Two-way minutes next to Wemby."},
    {"pri": 36, "name": "Matas Buzelis", "pos": "SF", "team": "CHI", "why": "Blocks and threes. Chicago will play him."},
    {"pri": 37, "name": "Alexandre Sarr", "pos": "C", "team": "WAS", "why": "Blocks. Raw offense. Cats leagues."},
    {"pri": 38, "name": "Donovan Clingan", "pos": "C", "team": "POR", "why": "Rim protection. Boards."},
    {"pri": 39, "name": "Yves Missi", "pos": "C", "team": "NOP", "why": "Blocks. Zion nights off the glass."},
    {"pri": 40, "name": "Jared McCain", "pos": "SG", "team": "PHI", "why": "Shot. Sixers need a second creator."},
    {"pri": 41, "name": "Brandin Podziemski", "pos": "SG", "team": "GSW", "why": "Connector. Threes and dimes."},
    {"pri": 42, "name": "Peyton Watson", "pos": "SF", "team": "DEN", "why": "Stocks. Denver wing minutes."},
    {"pri": 43, "name": "Julian Strawther", "pos": "SG", "team": "DEN", "why": "Spot-up threes."},
    {"pri": 44, "name": "Sam Hauser", "pos": "SF", "team": "BOS", "why": "Threes. That's the whole card."},
    {"pri": 45, "name": "Neemias Queta", "pos": "C", "team": "BOS", "why": "Blocks when KP sits."},
    {"pri": 46, "name": "Mitchell Robinson", "pos": "C", "team": "NYK", "why": "Boards and blocks. Foul trouble."},
    {"pri": 47, "name": "Josh Hart", "pos": "SF", "team": "NYK", "why": "Boards from the wing. Floor."},
    {"pri": 48, "name": "Aaron Nesmith", "pos": "SF", "team": "IND", "why": "Threes and D. Quiet starter."},
    {"pri": 49, "name": "Obi Toppin", "pos": "PF", "team": "IND", "why": "Energy four. Siakam rest."},
    {"pri": 50, "name": "T.J. McConnell", "pos": "PG", "team": "IND", "why": "Steals and dimes. Sixth-man stream."},
]


BK_SOURCES = [
    ("Hashtag Basketball Dynasty", "https://hashtagbasketball.com/", "Long compiled dynasty board, 400 deep."),
    ("FantasyPros Dynasty ECR", "https://www.fantasypros.com/nba/", "Youth-weighted expert consensus."),
    ("Basketball Monster Cats", "https://basketballmonster.com/", "9-cat stocks and bigs."),
    ("Hashtag Points", "https://hashtagbasketball.com/", "Points-league overlay."),
    ("ESPN Dynasty", "https://www.espn.com/fantasy/basketball/", "Youth board."),
    ("Yahoo Fantasy", "https://sports.yahoo.com/fantasy/", "Vet / this-year lean."),
    ("RotoWire", "https://www.rotowire.com/basketball/", "Guard-heavy."),
    ("CBS Sports", "https://www.cbssports.com/fantasy/basketball/", "Big-man lean."),
    ("The Athletic", "https://www.nytimes.com/athletic/", "Wing board."),
    ("Fanspo Dynasty", "https://fanspo.com/", "Prospect overlay."),
    ("Dynasty Nerds NBA", "https://www.dynastynerds.com/", "Youth dynasty."),
    ("KeepTradeCut NBA", "https://keeptradecut.com/", "Market tape, 300 deep."),
    ("BBall-Index", "https://bball-index.com/", "Impact / stocks."),
    ("NBA.com Fantasy", "https://www.nba.com/fantasy", "Short vet board."),
    ("Razzball", "https://basketball.razzball.com/", "Points overlay."),
    ("Basketball Reference ROS", "https://www.basketball-reference.com/", "Rest-of-season vets."),
    ("Draft Sharks NBA", "https://www.draftsharks.com/", "Prospect slice."),
    ("Late-Round Fantasy", "https://lateround.com/", "Wing streamers."),
]


PICKS = [
    {"name": "2027 1st", "pos": "PICK", "team": "", "rank": 28, "value": 0},
    {"name": "2027 Early 1st", "pos": "PICK", "team": "", "rank": 14, "value": 0},
    {"name": "2027 Mid 1st", "pos": "PICK", "team": "", "rank": 28, "value": 0},
    {"name": "2027 Late 1st", "pos": "PICK", "team": "", "rank": 42, "value": 0},
    {"name": "2027 2nd", "pos": "PICK", "team": "", "rank": 68, "value": 0},
    {"name": "2028 1st", "pos": "PICK", "team": "", "rank": 32, "value": 0},
    {"name": "2028 Early 1st", "pos": "PICK", "team": "", "rank": 16, "value": 0},
    {"name": "2028 2nd", "pos": "PICK", "team": "", "rank": 72, "value": 0},
]


def load_universe():
    meta, order = unique_universe()
    sources = build_sources(meta, order)
    keep = aggregate(sources, meta, min_n=1)[:400]
    guards = filter_group(keep, {"G"})
    wings = filter_group(keep, {"F"})
    bigs = filter_group(keep, {"C"})
    board = redraft_board(keep)
    rookies = []
    seen = set()
    for name, pos, team, blurb in ROOKIES_2026:
        k = bk_norm(name)
        if k in seen:
            continue
        seen.add(k)
        info = meta.get(k, {})
        rookies.append({
            "key": k,
            "name": info.get("name") or name,
            "pos": info.get("pos") or pos,
            "team": info.get("team") or team,
            "age": info.get("age") or "",
            "group": info.get("group") or pos_group(pos),
            "blurb": blurb,
        })
    for i, r in enumerate(rookies, 1):
        r["bk"] = i
        r["value"] = bk_value(i + 20)
    picks = []
    for p in PICKS:
        row = dict(p)
        row["value"] = bk_value(row["rank"])
        picks.append(row)
    return {
        "meta": meta,
        "keep": keep,
        "guards": guards,
        "wings": wings,
        "bigs": bigs,
        "board": board,
        "rookies": rookies,
        "picks": picks,
        "sources": sources,
    }
